spring:
  application:
    name: block-stream

server:
  port: 9000

aergo:
  server:
    # hostname: testnet-api.aergo.io
    hostname: localhost
    port: 7845

  account:
    address: AmLjs1v2URs1xSitMweA9nXqviK7ty1wF9SqACWniP8xNzHTEcSf
    wif: 47NKopnsGJrGDuGwVhZw1DCG4BQFRQ3JX7J8hSWwM43cvfDEHdcWa8TCBWEiixe6aTbdBHmaj
    password: 1234
